### ISSUE TITLE
Encode settings do not work

### ISSUE THREAD

**Issue by MariusSpangenberger** [yermak/AudioBookConverter#24]
no matter what settings I set in the output tab, it always encodes with the source files settings

tested with version 3.2 and 3.1

**Comment by yermak** [comment]
I will have a look over the weekend

**Comment by DGruwier** [comment]
Having a similar problem. In my case it doesn't even use the source file settings, it just defaults to 128kbps, when the original files are all 320kbps,  seemingly no matter what settings I pick.

**Comment by yermak** [comment]
Thanks for feedback. I will review the issue in more details.

Quick workaround: once set the frequency - click up or down arrows on the spinner - this should work (at least for the first book after run).
There is additional bug (or feature) in this area i unintentionally introduced while tried to use some javafx api instead of ffmpeg (which did not work at the end): checkbox - use file settings now just defaults to ffmpeg "auto" quality instead of keeping the same bitrate. 

I will review all encoding settings in next release shortly

P.S. Keeping same bitrate is kind of pointless as mp3 and m4b have completely different codecs thus keeping just bitrate does not make much.

P.P.S. sorry for slow reaction - got a new job and was quite busy last few months.

**Comment by yermak** [comment]
Fixed in version v3.2.1

**Comment by DGruwier** [comment]
> P.P.S. sorry for slow reaction - got a new job and was quite busy last few months.

I'm honestly just amazed that something came of writing here at all, that rarely happens with niche tools like these, thanks!
