### ISSUE TITLE
Bitrate is blank

### ISSUE THREAD

**Issue by metalollie** [yermak/AudioBookConverter#243]
Hi,
Since the latest update to 5.5.18 the bitrate pull down menu only shows “—“ after selecting my rate, when run in a minimised format. Also, Format, speed and Split By no longer display their full titles.. 
![42269040-6F7A-4DB0-BB14-15678728B2CE](https://user-images.githubusercontent.com/16440606/110836302-cb744780-8297-11eb-8cb7-7abd08db1aa5.jpeg)

**Comment by yermak** [comment]
I agree this could be considered as bug, but i suggest just resize window and make it slightly larger to allow all information to fit.
It's been real pain to adjust application to different screen resolution and scale settings on high res screens.
I think this bug could be fixed by resizing window, as far as i can see it's possible to do.
