### ISSUE TITLE
Wrong bitrate

### ISSUE THREAD

**Issue by metalollie** [yermak/AudioBookConverter#291]
Hi,

since upgrading to 5.5.23 my output file is only 128k, despite setting it at 320k or 256k. I’ve checked the source material which is 320k, and repeated attempts at creating the audiobook always have the same outcome, namely a 128k encoded version of the file.

Thanks!

**Comment by yermak** [comment]
Fix will be released in next version. I currently have some issues with build stability due to external dependency not working as expected. But I hope to resolve this quickly.

On separate note: program automatically select the highest bitrate from all files, however, i obvserved that quite often there could be publishers' into or something like this with much higher bitrate then all other chapters, so please be mindful when selecting high bitrate, it may not have impact that you expect
