### ISSUE TITLE
Merged file is bigger, with smaller cover art

### ISSUE THREAD

**Issue by AudiobookListener** [yermak/AudioBookConverter#310]
Was merging 39 M4B chapter files (1.01GB total) with AudioBookConverter, and noticed that the resulting file was larger (1.02GB). Not much, but strange as the 39 chapter files all had 66K of cover art. The the merged file seems to only have one copy but strangly the cover art size is now 50K.  Ran the same merge with inAudible and the resulting file size was a bit smaller than the individual chapter (1.00GB) files as expected.

Precise data for analysis
Cover art 39*66K=2574K/.33MB, 39*50K=1950K/.25MB
(1,084,541,330 bytes) 1084.5MB (on Disk 1,084,542,976 bytes) Merged by inAudible, 30 second merge time
(1,087,196,048 bytes) 1087.2MB (on Disk 1,087,275,008 bytes) 39 M4B files, each with 66K cover art
(1,096,307,629 bytes) 1096.1MB (on Disk 1,096,310,784 bytes)  Merged by AudiobookBookConverter, cover size now 50K, 80 second merge time

Seemingly, this paid product took 3x longer and expanded the result, whereas the freeware was faster and produced a smaller file.

http://malich.ru/duplicate_searcher which has the option to compare media files minus the metadata found merged audio not equal.

Perhaps we can make some sense of this? Thanks, -AudiobookListener

**Comment by yermak** [comment]
@AudiobookListener,
Thank you very much for feedback, i'm not sure if this a bug or general discussion.

First important thing to know when you merge existing M4B files - there is no real encoding happens in most of the cases, it's just copying files on the disk and muxing them. In most real life re-encoding scenarios, this time is very minor comparing to real time of actual re-encoding.
Secondly 3 times of time difference in this corner case scenario is easy to explain and works as designed: as all manipulation with audio files are happening in "TEMP" directory, so files are copied there first, this is generally useful when files are stored on network drive like NAS. And another round of copping happens due to use of parameter "-moveflag faststart"
Here is extract from encoder documentation:
```
By default the MP4 muxer writes the 'moov' atom after the audio stream ('mdat' atom) at the end of the file. This results in the user requiring to download the file completely before playback can occur. Relocating this moov atom to the beginning of the file can facilitate playback before the file is completely downloaded by the client.
-movflags faststart
Run a second pass moving the index (moov atom) to the beginning of the file. This operation can take a while, and will not work in various situations such as fragmented output, thus it is not enabled by default.
```
I do believe spending few extra-second during re-encoding is better then waiting while file loads during playback.

This could explain size difference as well, but i'm not sure about that w/o testing.

If you interested in further discussion share your files by link in cloud and send to my nick name @ gmail.com.
I will run a test have a look.

Please feel free to share link to inAudible (as i'm not sure what exact software you refer to), as AudiobookConverter is opensource software i'm really interested in community help to make it better.

P.S. On a separate note: to compare performance speed please select testing set where real re-encoding will happen (i.e. mp3 to m4b or m4b to mp3), i'm sure you will not be disappointed by AudiobookConverter performance.
