### ISSUE TITLE
Not honoring Quality Settings

### ISSUE THREAD

**Issue by Protektor-Desura** [yermak/AudioBookConverter#318]
When I edit an existing M4B or M4A file, and clean it up and want to reduce it from 128K bit down to 32bit it does NOT do that. I doesn't seem to make any difference what I change/set in the quality tab and just ignores it and uses the original settings/files regardless of what I pick/set.

**Comment by yermak** [comment]
Default behaviour do not re-encode AAC codec to AAC, however, i need to check if this behaviour correct when changing quality settings.
Will have a look in nearest future, not ideal workaround, but you could re-encode to ogg using some very high bitrate and then back to aac.

**Comment by yermak** [comment]
@Protektor-Desura ,
I looked into implementation details, indeed if source and target codec is the same then files WILL NOT BE RE-ENCODED (Ignoring quality settings). This was done for purpose as usually if you processing from AAC to AAC you probably are repackaging chapters or adding ArtWork, if you doing this for size - why don't use ogg (okay-okay, may not work on default book players)

This issue was already raised/discussed couple of times. 
Before:
1) Only 1-2 users had this issue/challenge
2) Could not come up with idea how to make UI to be self explanatory and not confusing for users.

I previously did not want to do this for reasons described above, but changed my mind now - nearly completed this (not tested properly) - will be released in next version (closer to X-mas)

**Comment by yermak** [comment]
Similar to #206

**Comment by Protektor-Desura** [comment]
It should import the settings from the original and if you don't change it then just remux it. If you do change the settings then to me it should honor those changes.

**Comment by yermak** [comment]
@Protektor-Desura ,
what if original files have different bit rate? I.e. when repackaging series of books into single Audiobook?

**Comment by Protektor-Desura** [comment]
Then you should be able to pick a rate to reencode all file into a single standard.

**Comment by Protektor-Desura** [comment]
Basically the code should be if selected bitrate=existing bitrate then remux. If selected bitrate<>existing bitrate then transcode.

if selected_bitrate = existing_bitrate then
       remux;
   else
       encode_at_new_bitrate.

**Comment by yermak** [comment]
@Protektor-Desura,
thank you very much for your note.
It will be implemented slightly differently, i will add force re-encode and make it more explicit.
There are too may parameters in output quality and it will be bad idea to make user to guess, how applicaton works now.

Current behaviour is determind: same codec = no re-encode, different codec - re-encode.

You suggest more unpredictible behaviour, what if user want to mix stereo to mono with the same bitrate?

Nevertheless, your problem would be fixed in next couple of days.

**Comment by Protektor-Desura** [comment]
> You suggest more unpredictible behaviour, what if user want to mix stereo to mono with the same bitrate?

I personally wouldn't allow it. The entire M4B file should uniform and consistent. It is pretty easy to convert mono to stereo and stereo to mono with ffmpeg.

**Comment by yermak** [comment]
fixed. added force re-encoding, so it will respect quality settings if you select this option.
Will be released with next version
