### ISSUE TITLE
Auto quality (bitrate) setting bug

### ISSUE THREAD

**Issue by g4dget** [yermak/AudioBookConverter#34]
Hi,

I just found this program and tried it out for the first time yesterday. I saw that 4.0 is brand new and you're expecting bugs, so I figured I'd report the ones I found. Anyway, I tried creating a book and was surprised that the resulting m4b file was nearly twice as large as the original folder (~720MB vs. ~400MB for the original). After checking the files, I found out that the original mp3 files were 64kbps but the audiobook created with the auto quality setting used 128kbps. I assume this is a bug as the bitrate should not increase from the source mp3 file to the resulting aac (m4b) file.

**Comment by g4dget** [comment]
Plus a small nitpick: The bitrate units, kBs/s, shoud be kbps or kb/s.

**Comment by yermak** [comment]
g4dget, this issue is known, however, won't be fixed as there is deep underlaying issue with quality of media information i.e. duration (issue #21 ) which will require rework anyway. 
Please consider this option as default for m4b not "smart" auto, in particular it's not correct to compare bitrate between mp3 and m4b - as encoding alogirthms are different. 
However, i see your point - that how program used to work in previous version, using max bitrate of all files to set bitrate for the book.
From my observation it's safe to set m4b bitrate lower then mp3. If you know what you are doing -please use manual mode. Default is more useful for less experience people who is keen to convert 320kb/s books without thinking about resulting file size.

**Comment by g4dget** [comment]
Yermak. Thanks for the in depth response and for all the time you've put into this software. It's super useful and there's really nothing else out there like it.
