### ISSUE TITLE
Book Number Not Appended to File Name (for series)

### ISSUE THREAD

**Issue by g4dget** [yermak/AudioBookConverter#35]
Hi,

This is for version 4.0. Not sure if I'd call it a bug or a feature request, but here it is...

When creating an audiobook with "series" and "book #" metadata, the series is added to the file name automatically, but the book number is not. Of course the file name can be manually edited, but it would make sense to add it automatically within the brackets like this: .... [Series Name 0X] .... where X is the book number.

**Comment by yermak** [comment]
It's fixed in 4.x branch, will be included in next release.
Please note file name format is configurable in AudioBookConverter-xx.properties located in Roaming user profile and by default is the following
`<WRITER> <if(SERIES)>- [<SERIES><if(BOOK_NUMBER)> -<BOOK_NUMBER>]<endif>] <endif>- <TITLE><if(NARRATOR)> (<NARRATOR>)<endif>`
