### ISSUE TITLE
Title "-1" suffix

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#37]
The m4b file titles always have the "-1" suffix.
![ab](https://user-images.githubusercontent.com/43350149/74971133-e02d3580-541f-11ea-9098-502bf8d535f2.jpg)

**Comment by yermak** [comment]
Hi Kazaa3,
Yep, i know about this issue for book with only 1 part, this number is very usuful if you use multipart books. Otherwise while syncing in iTunes all parts looks exactely the same in sync window and there is no way you could guess which files too sync.
I will have a look how to not add the number if there is only one part.
I believe this is not critical issue though

**Comment by yermak** [comment]
Fixed now and will be released in version 4.1
