### ISSUE TITLE
Audiobook squeaking on iPod Classic 60gb 5th gen but not on Nano 2nd and 3rd gen?

### ISSUE THREAD

**Issue by v-marinkov** [yermak/AudioBookConverter#429]
I converted .mp3 audiobooks into a single .m4b. The file is 64kbps 44.100 kHz as the original mp3s and even though it plays on my iPod Classic 60gb 5th gen, it has a heavily distorted sound which can be described as squeaking. The file works perfectly on PC and iPod Nano 2nd and 3rd gen.

Selecting 128kbps even if the original file is 64kbps improves the situation but the squeakes are still unbearable. The clip threshold also has no effect. Combining the chapter mp3s into a single mp3 also works perfectly, so it seems something goes wrong in the conversion to .m4b. I have another .m4b audiobook which works perfectly and iTunes reports 128kbps and "encoded with: Chapter and Verse V 1.5" for it. I can't launch Chapter and Verse on Win 11.

I learned iPod Classics don't open audiobooks above 15h (and this one is way shorter) but is there any other limiation on the audio parameters?

**Comment by yermak** [comment]
Unfortunately, i lost my ipod classic (that device actually triggered cration of this software). So, can't test properly.
What I could suggest, is fallback to very early version i.e. V2 and see if has the same issue. Earlier versions used fraunhofer codec which i stopped suporting due to license limitations.

Another thought is ffmpeg was supporting undocumented output format ipod (which probably triggered aac to use compartible version). They (ffmpeg) could stop suuporing it. I can't prove it, need to spend more time researching...

Please ler me know if older version works

**Comment by yermak** [comment]
Right. Ipod format is documented and supported. However, i lost it when added filesize optimisation feature. I will try to restore it next release, however, i will not be able to test it.

**Comment by v-marinkov** [comment]
@yermak Thanks so much! v2.11 works perfectly and I love the simplicity of it - use the source quality and auto make chapters.
In any case, I'll be happy to test any new additions on the Classic if you need me to.

**Comment by MarkWllms** [comment]
I have the same issue with my iPod mini. 2.11 also works fine for me.

**Comment by yermak** [comment]
Partially fixed, continue to encode with existing profiles, but restored format ipod for output files, which should ensure files are compatible with ipod.
Will be released after 6.4.1
