### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by HenryMontrose** [yermak/AudioBookConverter#43]
Hi just an easy one, **the artwork**, always duplicates, as you work through the bottom tags to check your settings, always seems to add the artwork twice (and no there are not 2 photos - I always check).. thanks

**Comment by yermak** [comment]
@HenryMontrose,
Could you please check if you mp3 contains artwork within mp3 file and another file in directory?

The way program works it extract all unique images from mp3 file and check directories from which files were added to load all possible images. You need to select the one you like the most.

Currently uniqueness is checked by checksum (crc32) of the image, so if you have jpg image within mp3 as artwork and png in directory (or they just different size or jpg quality) - even if they look same (or very similar) formally they are 2 different files as checksums are different. Creating more intellegint comparision - is a separate interesting task - as we need to define what similar means...

As far as I noticed 2 or more artworks do not impact the file and allowed by format.


P.S. There is chance that there is a real bug with checksum, but even if I fix it  - this can't be resolved completely, due to above.

**Comment by HenryMontrose** [comment]
Aha.. Sherlock is alive and well!!, you are so right, it copies both the artwork, and the mp3.. see Knew you could fix it.. thanks again
