### ISSUE TITLE
Series info overwriting Title

### ISSUE THREAD

**Issue by Bugmaniac71** [yermak/AudioBookConverter#437]
As stated above, I'm creating 3 books. All in same series. I enter separate titles. All Same series, books 1-3. Once teh books are created and I reopen them the title has been set to same as the series name.

Latest Windows Version of ABC (All users) 6.1.1.

**Comment by yermak** [comment]
@Bugmaniac71
Did you create 3 books as 3 separate jobs? 
Or did you added 3 books as 3 parts into single job? Currently there is no configuration on parts level.
So you need to chose either you create each book separately and title is preserved. Or your create bulk with parts - in this case you can't preserve title in parts.

I would appreciate your response.

**Comment by Bugmaniac71** [comment]
Hi. Evertime I create a book, the series info overwrites the title info.
Happens every time.

**Comment by yermak** [comment]
@Bugmaniac71 , thanks!

**Comment by yermak** [comment]
@Bugmaniac71 , this is confusing...
Resulting book contains exactly what filled in title and series, so, probably I misunderstood your report

If you are talking about pre-filling text fields when mp3 book is imported, so that's expected behaviour and I deliberately chosen it.

In mp3 normally you can't store series and title, typically and most common - mp3 file's titile is just "Chapter 1" at best, and book name is stored in album. Series is not stored at all or stored in random field. i.e. comment.
So, i fill title from album field, and keep it as series as well - there is no better option and quite common that for the first book series and title name are same.

If you could give better logic - i will be happy to consider chaning program behaviour.

**Comment by Bugmaniac71** [comment]
Very strange, i've just reloaded ABM to retest and its not doing it now and
havent updated. Close the ticket please - I'll keep an eye on it and see if
it starts happening again - thanks for looking though.

Regards
Carl.
