### ISSUE TITLE
Missing properties file

### ISSUE THREAD

**Issue by abuhamsa** [yermak/AudioBookConverter#444]
Hi in your FAQs (https://www.recoupler.com/products/audiobookconverter/faq) you state:
![image](https://user-images.githubusercontent.com/1926397/193142889-b0971569-c117-4a5c-a6b2-3b7fee09c4f5.png)
But with version 6.1.2 I cant find this file:
![image](https://user-images.githubusercontent.com/1926397/193143174-2ff4c655-0d89-4271-ba24-e850d53f9dcb.png)

Is this a bug or is it stored somewhere else?

**Comment by PepperRobb97** [comment]
I'm having this same issue. I can only get the properties file to show up in version 5.6.2

**Comment by yermak** [comment]
Hello, 
Unfortunately properties files are replaced with internal database, due to consistency issues - i could not fix.
I will add feature of edditing their content via UI in the future, for now if you heavily dependend on custom format of properties - you can use version 5.6.2

**Comment by PepperRobb97** [comment]
Thank you yermak. 
I've been using the property file to edit Chapter customization specified in the FAQ above, amongst other things. I've pretty much been able to set things up so that the software works exactly how I want it to. Having you include this in a UI feature enhancement would be a wonderful addition to the software that I personally think would benefit EVERYONE and would enhance their use of it even more. 
I also believe that a UI version of these features would play a dual role. It would simplify the process, as the preferences are RIGHT in the program. It would also give you the chance to make it easier to understand.  Without having to update your documentation, you can de-clutter the information in the preferences area, which is all one big wall of text. Maybe consider using check boxes to to tick off what you want to include or not. Yes the quick and easy way to make this work would be to just import the text file and have users fill out what they need. But to make it more user friendly? That would REALLY make it something users would be able to comprehend easily and not need to be polished later on. It also reduces the need to answer questions and update documentation in the future. Of course, it's all just a suggestion and your decision. I appreciate you even letting me make one.
Regardless of how you decide to proceed, I want to thank you for considering this since the file itself cannot be fixed and for continuing to fix and enhance a really cool piece of software during the time you have available. The fact that you are WILLING to even do this in a UI format is wonderful. So thank you. I look forward to when you are able to get the enhancement working in a future working version so I can finally upgrade to a newer version than what I've been using this past year or so.

**Comment by yermak** [comment]
Fixed in 6.4.1. All settings are now editable in settings :)
