### ISSUE TITLE
File Explorer doesn't come up when trying to convert/save file

### ISSUE THREAD

**Issue by codyjanak** [yermak/AudioBookConverter#465]
I am not able to convert any files. When I click the Start button (or Convert > Start), nothing happens.

This started about a week ago when I converted one audiobook just fine. When I tried the next one, it just wouldn't work. I ignored it until today when I tried again and same issue. The was with the Steam version. I installed the Choco version and same issue. I've tried multiple files and they all do the same thing.

I wasn't able to find any active issues that resemble this, but please point me in the right direction if I just missed it.

**Comment by rhayes1** [comment]
i'm having the same issue!

**Comment by woessmich** [comment]
Same here. Used to work, now does not.

**Comment by Figgs** [comment]
Same here. Gave it a few weeks to see if it got sorted, still wont convert anything.  Also tried reinstalling and it didn't help.

**Comment by KinsmanWyn** [comment]
Having the same issue. I was converting a series of books one at a time and clearing after each one before starting the next one then it hung (the app) but the file appeared to finish and was playable through VLC. Ever since the Start button does nothing. it mouses over and highlights but doesn't appear to trigger any action.

Interestingly, that file won't transfer to my phone. I use a usb c to c cable. Very strange the way it just stopped working I the middle of things. Any help or a fix would be really appreciated.

**Comment by codyjanak** [comment]
Does anyone have a recommendation for another similar app? The last Steam update was for Mac in October of last year, so maybe they aren't updating this anymore. My backlog is really growing, so I need to find an app that actually works.

**Comment by Figgs** [comment]
So I had the same problem (add files hit start nothing happens). I did a bunch of digging through forums and found something about deleting files in the appdata folder. It works perfectly again.  When I’m home later I’ll try to find out exactly what I did, but this might point you in a direction for some google searches.

**Comment by Figgs** [comment]
https://github.com/yermak/AudioBookConverter/issues/424#issuecomment-1179700044

**Comment by codyjanak** [comment]
@Figgs You're the best! That worked for me.

**Comment by yermak** [comment]
Try to use Repair function in System menu.
