### ISSUE TITLE
Does not "Start," Nothing Happens; Solution in thread 489 does not work

### ISSUE THREAD

**Issue by jaudio101** [yermak/AudioBookConverter#492]
I am having the same issue as here: https://github.com/yermak/AudioBookConverter/issues/489

However, there is no application data folder for Audiobook Converter that I could find to delete. Can you provide another possible solution for this problem? The files show up to convert, but when I click Start, nothing happens.

**Comment by walenchao** [comment]
The AppData folder is hidden by default - easiest way to get there is just type - %appdata% and press Enter in your search bar in the start menu to open it if you have access to it. 

To see it, you have to go to C:\Users\[your username] then click View and tell it to Show Hidden items in that folder - the AppData folder will appear there. In Windows 11 that option is:

![image](https://github.com/yermak/AudioBookConverter/assets/150093808/03c428e6-89e6-44cb-b836-0c03a6db037d)

Here ^

You can also do this by Right-clicking and then going to Folder Options > View tab > Show hidden files and folders:

![image](https://github.com/yermak/AudioBookConverter/assets/150093808/e873b23b-bd5d-45e9-bb1f-05083871b0bb)

Inside the AppData folder is the AudioBookConverter folder, which you can delete to use the app again (I have to do this between each book, personally)

![image](https://github.com/yermak/AudioBookConverter/assets/150093808/9e3c8f7e-2826-4940-b9f6-bd8534706d23)

**Comment by thew1se** [comment]
I too am having problems using version 6.2.6

I successfully converted 4 books.

On the 5th it would allow me to see the chapters as expected, but then when i click "start" nothing happened.

There is nothing in the log that looks out of the ordinary.

Here is a rundown of troubleshooting steps taken:

1. I uninstalled the program and deleted the folder in the users/name/appdata/romaming/ folder.

2. Then reinstalled.

3. Opened the program and tried again with the book that didn't work.  Clicked start, nothing happens. (Interesting note that when I click "Open folder" it goes to the last folder I used). 

4. Tried again with uninstalling and deleting folder and rebooting comupter. Same issue, and same issue with the folder opening again at last folder.

5. Also, I tried opening an older book which I had done successfully, and it didn't work. 

6. Cleared the book and tried to open another book.  Then it listed the audio files of the previous book.


I believe this is a memory issue because of the errors occurring with:

1. opening the same folder even though it was reinstalled.
2. opening a new book, but the audio files tab lists the old book.
3. although I installed 6.2.6 (I beleive the newest version) i still get a prompt that there is a new version.

Hope this helps!

**Comment by yermak** [comment]
@thew1se,
Thank you for reporting.

I assume you are using windows.

Could you please try to fix it by cleaning registry (run regedit)
HKEY_CURRENT_USER\Software\JavaSoft\Prefs\uk\yermak\audiobookconverter

And remove registry key /Audio/Book/Converter-6.2.6

I moved all settings from files/database to standard ways of storing preferences - hoped it will be less of an issue.

Please let me know if it works.

**Comment by yermak** [comment]
All those problems (start does not work) seem to happen because settings somehow currupted. I never experienced it myself, so I struggle to reproduce the issue to find a root cause of the issue

**Comment by yermak** [comment]
Try to use 6.2.7 and if problem appear use Repair in About menu.
Hope it helps

**Comment by yermak** [comment]
This issue no longer valid from 6.2.x

**Comment by thew1se** [comment]
Yes using windows 11.    I deleted registry and installed latest version 6.2.10.  Seems to be working again but have only done one book so far.  Thanks!
