### ISSUE TITLE
Changing quality settings after converting a file does not seem to work (App has to be restarted)

### ISSUE THREAD

**Issue by turtle12** [yermak/AudioBookConverter#527]
I have found, when playing around with the quality settings, that any changes you make don't have any effect after having already converted a file, the quality settings will always remain the same as for the first job, only restarting the App fixes it for me.

Some other questions I have:
1. Regarding the AAC VBR-quality settings, which gives the highest quality, 1 or 5? From my testing it seems to be 1 (though normally it is the other way round in ffmpeg for me at least)
2.  Which AAC encoder is used? Apple (presumably the best), Libav ("worst"), FDKAAC (2nd best after Apple)?

At last I want to thank you for making and providing this really useful tool!

**Comment by yermak** [comment]
I need to check quality settings, as I did major changes in quality settings, there could be some bugs.
1. 5 should be the best, and that's leads us to your second question... as vbr quality depends on encoder.
2. unfortunately, apple and fdkaac has some issues to be distributed as open source... so I had no choice to fallback to ffmpeg native (libav)...  earlier version of programs were using ffmpeg with fdkaac built-in, but I had to remove them due to licencing issues. (I consider to return support of ffmpeg with fdkaac, but allow users to build ffmpeg themselves, but this could be too much for most of users, same with apple - I may support apple encoder on macOS platforms (but that's in the future)

Returing to you point re VBR quality, originally quality seetings were inherited from FDK which were in the range of 1-5, but to use ffmpeg native encoder (which is in between 0.1-2) - It's currently calcuated  as 0.5 + vbrQuality * vbrQuality * 0.06, which gives 2 at settings of 5 and so, on.

There is an option to significantly improve quality of encoding by using more advanced encoding parameters, but it will be about 2*x times slower - here is the poll https://github.com/yermak/AudioBookConverter/discussions/512

**Comment by turtle12** [comment]
Thanks for the quick reply, I feared that you had to use lobar due to the licensing issue. It’s not a big deal for me since I found that I can convert files first with my ffmpeg that has fdkaac and then your tool will usually avoid re-encoding.

I think there are definitely some bugs with the quality settings. I can confirm that at least on my system vbr 1 leads to the highest bitrate output (for ex. around 190 kbits aac from a 160 kbits mp3, vbr 5 gives around 70 kbits).

**Comment by GNO21** [comment]
There are definitely some oddities here.
The options don't appear to take affect as Turtle12 mentions.  

They also seem to report wrong in the end file, if it works.
Most of the time it doesn't actually combine the files, it just re-encodes them.  

So 12 mp3's end up being 12 m4b's, instead of 1 m4b.  

Additionally, if the input is a VBR AAC file, and "avoid re-encode" is selected, the resulting file reports itself as a CBR.

**Comment by chupzzz** [comment]
Confirming: issue with quality settings still persist (v6.2.10)
Have to restart the app every time for new settings

**Comment by yermak** [comment]
Should be fixed in next version after 6.4.1

**Comment by yermak** [comment]
> Most of the time it doesn't actually combine the files, it just re-encodes them.

Splitting by chapters is the bug of the same nature, changes in settings did not have effect until restart.
