### ISSUE TITLE
Presets are reset to the default on version update

### ISSUE THREAD

**Issue by weak-head** [yermak/AudioBookConverter#597]
### Description

When upgrading the app (e.g. from 6.3.0 to 6.4.0) the configured and saved presets do not persist and are reset to default.

### Expected behavior

When updating the application using the MSI installer it is expected that:
- All manually created and configured presets should be left intact.
- All manually removed default presets should not be added again.
- No new presets should be created when the app is upgraded (differs from the first time install).

### Environment info
App Version: 6.2.9 -> 6.4.2
OS: Windows 11
Installation method: Single User installation

**Comment by yermak** [comment]
Hi,
Thank you for feedback.
This is not really a bug, but intentional behaviour:
I wanted to have freedom to change settings format w/o complex migration from version to version.
Also, there used to be issues with settings in the past, so migration to new version allowed user to "restore" program.

I would treat this as "feature request", maybe alternative is to keep settings if there is no braking changes, but reset if changes are significant.

**Comment by weak-head** [comment]
Thank you for the feedback. Not sure how many users are affected by this behavior or feeling a need to change it.

Below is my use case and the motivation: 
I have a profile for each bitrate that I'm interested in. My typical profiles include at least the following: 64 kbps, 80 kbps, 96 kbps, 128 kbps, 192 kbps, 256 kbps, 320 kbps. So, each time I update the application I have to manually re-create these profiles and remove the default ones (because the list with profiles becomes too long to navigate). 

I believe this is a rare use case and the majority of users don't need this kind of complexity with multiple profiles.

**Comment by yermak** [comment]
I probably will go for keeping settings between versions, in case there will be breaking changes (which is unlikely in near future) - you will need to re-work.
