### ISSUE TITLE
Chapter mode tab

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#63]
After going into chapter mode, I didn't see any option to go back to file mode to change the order of the files. The use case is to add an additional file while in chapter mode. Or change the file order after using chapter mode. A solution could be a separate tab for chapter mode.

**Comment by yermak** [comment]
There is no option to go back to files mode. It's possible to do so, but then all changes in chapters mode will be lost.
If chapter mode you could reorder chapters (by defult chapter will contain just one file). It's less convinient but possible.
You still can add files in chapters mode, they will be auto-imported (as you are in chapters mode).
(Oops, there is new bug of showing files tab again), while new files are added into new part.

**Comment by yermak** [comment]
@Kazaa3, do you think going back to files mode loosing all chapter changes - that's right behaviour?
Why not to clear and start again?

**Comment by Kazaa3** [comment]
I think from the user's view point  it would be good that all changes to the menu are preserved, even if additional files are added.

**Comment by thew1se** [comment]
agree, trying to re-add the files loses all entered fields.

**Comment by yermak** [comment]
Retested this on current version 5.2.0
1) Added 3 files.
2) Imported chapters -> 3 chapters created
3) Updated chapter information of the 1st one -> informaiton is reflected
4) Added yet another file -> Part 2 is created (as i consider this as new addition), 1 Chapter is created in Part 2. Information about Chapter 1 in Part 1 is still there.

Consideration on 4th step: I believe people mostly add entire book in single go. I would add once more batch only if add another book from a series. That's why second part is created.
If files need to be added to first book you need to select both Parts and press combine - it will result a single file.

Flipping back and forth between files and chapter mode will result unpredictable behaviour.
Let's imagine:
I add files A and B, import chapters and combine both files to single chapter.
Flip back to files and add file C and then I reorder files into A, C, B.
Question would i see if go to chapters? is C within same chapter? Or not? 

So import chapter is oneway process - too many updates could be made in chapters mode
