### ISSUE TITLE
Undo changes

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#65]
An undo changes option would be amazing. The only option at the moment is a restart.

Use case: Changed chapter menu incorrectly by mistake.

**Comment by yermak** [comment]
I believe if you mean undo when editing chapters titles?
I think you could reconfigure them to original state, as non of information displayed in the first launch should be lost...

Well, it's possible in theory to track all history of all changes in chapters titlels, and then use this history to do undo, but how common is this schenario?

**Comment by thew1se** [comment]
I just clicked split by accident and couldn't figure out how to get it back to original...so agree with an undo option.  

I'm a new user of this starting today.  I read the documentation and watched the video but still not clear on how the chapters work.

**Comment by yermak** [comment]
@thew1se 
If you split by mistake books into parts, select those 2 partse and click combine.
That's why you don't need undo when split/combine.
However, current version has bug #84 which make it unpredictable.
@Kazaa3,
I'm still wondering about you scenario, is it still relevant? Earlier version could have a bug when informaiton is updated even if you did not press save. I believe it's now updated only when you save it.

Alternatively in chapter edit menu - we could consider to have button - reset to original state... not sure if it's needed though...

**Comment by yermak** [comment]
I will close this issue for now, i will not implement in this format anyway.
It's seem most of the issues with overall usability rather specific need to undo (this mostly happens when people don't learn how to use program yet)
